---
- hosts: linuxnodes
  tasks:
          - name: printls - Exists
            shell: ls /etc
            register: exists
            until: exists is succeeded
            retries: 10
            delay: 2
